- name: aFormalParrot
  username: CrazyDuck24
  description: Keeper of the courthouse, maker of website.
  discord_id: 1008254028649607249
  avatar_id: a4f323c598b834d617513afee4d6f3e1

- name: MineKey98
  username: MineKey94
  description: Co-Builder of courthouse, maintainer of Bigstone Dev's weekly competitions.
  discord_id: 783091835295105055
  avatar_id: 967bea8289107cedd8543321771d5204

- name: cal
  username: Codeapotamus
  description: Co-Builder of courthouse, knows minecraft game mechanics better than anyone.
  avatar: ../assets/images/discord_cal.png

- name: BastienA
  username: BastienA
  description: Co-Builder of courthouse, has many cool things at his plot.
  discord_id: 639413750893379595
  avatar_id: 0fa335b98f4d6af2391a061006a5faeb

- name: Huckle
  username: "TheHuckle; h2bi"
  description: built the ceiling for courthouse. that's about it.
  discord_id: 554368136552644638
  avatar_id: 94ed368717742f0cce315f2315d550e6

- name: LimeLight
  username: B747_8i
  description: built the ceiling for courthouse with huckle.
  discord_id: 942397551167016960
  avatar_id: c3834d2790a62f6abcddd7eddea0c076
