name: Deploy Dev Branch to Pages

on:
  push:
    branches:
      - dev  # triggers on dev branch

permissions:
  contents: read
  pages: write
  id-token: write

environment:
  name: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # change if site is in subfolder

      - id: deployment
        uses: actions/deploy-pages@v4

      - name: Show preview URL
        run: echo "Preview URL: ${{ steps.deployment.outputs.page_url }}"